name: Deploy Productierv1 (Stage)

on:
  push:
    branches: ["stage"]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy productierv1 (stage)
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
          ssh-keyscan -H 216.250.122.193 >> ~/.ssh/known_hosts
      - name: Deploy to Stage Server
        run: |
          ssh scripts@216.250.122.193 << 'EOF'
          set -e
          echo "🚀 Running deployment script..."
          bash /var/www/deploy-scripts/productierv1-stage-deploy.sh
          
          echo "Productierv1 Stage deployment completed 🚀"
          EOF
